kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
android.useAndroidX=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.apple.xcodeCompatibility.nowarn=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m
KEY_STORE_PASSWORD=your_keystore_password
KEY_ALIAS=your_key_alias
KEY_PASSWORD=your_key_password
org.gradle.warning.mode=none
