name: iosApp
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [iosApp]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: net.notipv6.ipv5
      DEVELOPMENT_TEAM: "USV5Y46UH8"
    preBuildScripts:
      - script: |
          cd "$SRCROOT/.."
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
        name: Compile Kotlin
    dependencies:
      - framework: ../composeApp/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/ComposeApp.framework
        embed: false
